### PR TITLE
Fix travisci build

### LINKED ISSUE #10: Deploy chef-file on supermarket.chef.io (optionally rename it)
I've recently published my artifact-deployer cookbook on supermarket.chef.io, but since it depends on chef-file, it cannot be entirely resolved on supermarket, forcing to define a `Berksfile` on each project that wants to use it.

Using [stove](http://sethvargo.github.io/stove/) it's very simple to setup a release process and publish on supermarket ([artifact-deployer uses it](https://github.com/maoo/artifact-deployer/blob/master/RELEASE.md))

Not sure if the name "file" for the cookbook is too generic and/or misleading with the Chef `file` resource; it would be worthwhile to change name before publishing.

Thanks!
  mao

### PR DESCRIPTION
**Pull request by mvdkleijn**
Hi there!

I believe this should fix #10. Most changes speak for themselves I guess. I removed the lock files for Berksfile and Gemfile since those are usually not committed. Also, I'm unsure as to why you removed the matchers earlier since I believe they are needed... so I added them back.

### CODE REVIEW

**Comment by mvdkleijn** [comment]
Hmm, not sure why it fails here. Ruby 2.0 & 2.1 fail but 2.2 works in Travis. Locally it seems to work with 2.1.5 and 2.2.3 just fine... will have to figure this out later.

**Comment by jenssegers** [comment]
Weird. I did change from using 'attribute' to 'property' in the resources.

**Comment by mvdkleijn** [comment]
Well starting with chef-client 12.5 release they changed `attribute` into `property`.

The builds use chef 12.4 when they fail and the working 2.2.3 build uses 12.5 so that makes sense at least. Rubygems.org says chef 12.5 requires ruby 2.0.0 or above so that shouldn't be a problem either. I'll have to dig into it a little more, must be a dependency somewhere.

**Comment by jenssegers** [comment]
Did you make some more progress, or should I merge it like this?

**Comment by mvdkleijn** [comment]
Sorry, I had a bit of the flu. Are you stuck on those failing ruby versions? If not, the simplest method would be for me to just remove all ruby versions except 2.2.3. :smile:

**Comment by mvdkleijn** [comment]
note that you might want to add `cache: bundler` to the travis ci config file to speed up future builds. (first build after adding it will cache the gems)

**Comment by jenssegers** [comment]
@mvdkleijn Do you if it would be best to revert to attributes to support older Chef versions?

**Comment by jenssegers** [comment]
Never mind, looks like the new resource structure is just not compatible with older versions regardless of attributes or properties

**Comment by mvdkleijn** [comment]
I think that is correct. In my cookbooks I test for 2.2.3 but nothing lower.

**Pull request merged**
